name: CI/CD - Build e Publicação no Docker Hub e Render

on:
  push:
    branches: [ "chore/configure-workflow" ] 
  workflow_dispatch: 

env:
  APP_NAME: simbia-web

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Login docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Gerar metadados da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Construir e Publicar a imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

